export const SET_SEARCHED_MOVIES = 'SET_SEARCHED_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const RESET_SEARCHED_MOVIES = 'RESET_SEARCHED_MOVIES';
export const RESET_POPULAR_MOVIES = 'RESET_POPULAR_MOVIES';
export const IS_SEARCHED_MOVIE = 'IS_SEARCHED_MOVIE';
export const SET_SEARCHED_VALUE = 'SET_SEARCHED_VALUE';
